spring:
  # 默认环境
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
server:
  port: 8090
  reactive:
    session:
      timeout: 86400
  address: 0.0.0.0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete